version: "3.7"

services:
    mysql:
        image: mysql:8.0.30
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=
            - MYSQL_ROOT_PASSWORD=
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci




